# Generated by Django 4.1.7 on 2023-04-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='log_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/thumbnails/no_thumbnail.jpg', upload_to='images/thumbnails'),
        ),
    ]
