# Generated by Django 4.1.7 on 2023-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_allcats_picseries_singlepic_seriescats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcats',
            name='cat',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
