# Generated by Django 4.1.7 on 2023-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_allcats_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picseries',
            name='heroIdBigPic',
        ),
        migrations.RemoveField(
            model_name='picseries',
            name='heroIdThumbnail',
        ),
        migrations.AddField(
            model_name='picseries',
            name='heroId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singlepic',
            name='thumbnail',
            field=models.ImageField(default='images/thumbnails/no_thumbnail.jpg', upload_to='images/thumbnails'),
        ),
    ]
