# Generated by Django 4.1.7 on 2023-04-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_remove_picseries_heroidbigpic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picseries',
            name='heroPath',
            field=models.FilePathField(default='images/thumbnails/no_thumbnail.jpg'),
        ),
    ]
