# Generated by Django 4.1.7 on 2023-04-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_picseries_heropath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picseries',
            name='heroId',
        ),
        migrations.RemoveField(
            model_name='picseries',
            name='heroPath',
        ),
        migrations.AddField(
            model_name='picseries',
            name='hero',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
